steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcb-sample/gcb-sample:tag1', '.' ]
images:
- 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcb-sample/gcb-sample:tag1'
