steps:
- name: "asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcb-sample/gcb-sample:tag1"
  entrypoint: "cp"
  args: ["-r", "/gcb_sample", "/workspace/"]

- name: "asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcb-sample/gcb-sample:tag1"
  args: ["-m", "gcb_sample"]
